### ISSUE TITLE
Can't access the API host.

### ISSUE THREAD

**Issue by worsteggs** [weng-lab/SCREEN#106]
Dear team,
thanks for your brilliant work.

And I want to get the linked genes of all cCREs. I see that I can get these genes by graphql API. Follow your description, I learn how to use graphql query, but I can't access the screen API you provide-"The host url for the API is https://screen-api.wenglab.org/graphql." I think it probably due to some network or firework issue.
Here is my test using your example of the command-line with cURL:
`curl 'https://screen-api.wenglab.org/graphql'\
 -H 'Content-Type: application/json'\
 -H 'Accept: application/json'\
 --data-binary '{"query":"{ globals { byAssembly(assembly: GRCh38) { tfs } } }"}'`

And here is the output:
`curl: (7) Failed to connect to screen-api.wenglab.org port 443: Connection refused`

Besides, when I directly visit the 'https://screen-api.wenglab.org/graphql' on my chrome, it says "Cannot access this site screen-api.wenglab.org The connection was terminated unexpectedly".

I hope to get your help. If you need any more information, plz let me known.

Sincerely,
Eggs

**Comment by purcaro** [comment]
Sorry about that! We are fixing today.

In the meantime, you can go directly to the graphql endpoint at
https://api.wenglab.org/screen_graphql/graphql

Thanks for trying out the API!

**Comment by worsteggs** [comment]
Thanks for your reply.

I tried the graphql endpoint, and it works. But I want to put it in R, for I have a large list of ccres to get. So I need to run it in programs like R or something else rather than a website.

Anyway, thanks for your works, and once the API host works again, plz tell me.

Yours,
Eggs

**Comment by purcaro** [comment]
the api.wenglab.org site is the API site; the screen-api.wenglab.org URL just redirects to it.

You can query https://api.wenglab.org/screen_graphql/graphql from R. When you go to the site in a webbrower, the graphiql frontend will display.

https://www.gatsbyjs.com/docs/how-to/querying-data/running-queries-with-graphiql/

**Comment by worsteggs** [comment]
Thanks ，@purcaro ! It's work!

**Comment by worsteggs** [comment]
Hi @purcaro,
thanks for your answer again! But I have another small question. Could I get the original cCREs-linked gene table directly? Because I want to get the linked genes of all cCREs. If I query it one by one using the loop, it seems will take a long long time to get the whole cCREs-linked gene.

**Comment by purcaro** [comment]
Hi! 
What query are you doing right now?

@Jill-Moore notes that we don't have those tables available at the moment. It is something we are planning on adding in future versions as methods for prediction enhancer gene interactions expand.

**Comment by worsteggs** [comment]
Hi, @purcaro, sry for replying so late. I missed the notification from github.

Here is my code for query data. And ccreid is each ccREs id, like "EH38E1310221".
`{
 ccre(accession: ',ccreid,') {
     accession
     details {
       linkedGenes {
         gene
         celltype
         method
         dccaccession
       }
     }
   }
 }`
