### ISSUE TITLE
Download is broken on https://screen.wenglab.org/

### ISSUE THREAD

**Issue by mattiasaine** [weng-lab/SCREEN#118]
Hi, 

Excuse me if I'm in the wrong place, seems you guys are behind https://screen.wenglab.org/. Something is off with the data download link.

All track downloads yield "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>"

**Comment by hpratt** [comment]
Hello, thanks for catching this! I restarted our download API and the problem seems to have resolved. Please let me know if you're still experiencing issues and if so which particular tracks you aren't able to download.

**Comment by mattiasaine** [comment]
Yes seems to work. Have download of "GRCh38-ccREs.bed" as part of an annotation pipeline that just broke suddenly. Think last time I ran it was mid Jan. Back then link was http, now https it seems.

Still throws an error that md5 from download today is not same as back then but as far as I can see the downloaded file is identical when I read it from fresh download and one I happen to have since last run.

So think all is well. Thanks!
