### ISSUE TITLE
Accession number searching seems to be broken

### ISSUE THREAD

**Issue by skeitaa** [weng-lab/SCREEN#130]
Hello, I don't know if this is the right place, but I'm trying to use https://screen.encodeproject.org/ and would need to search for cCREs accession numbers (formatted like EH38E1613479) on the website in order to find the target genes for that specific cCRE. The problem is accession number searching always results in a blank page on my side. I tried multiple browsers and accession numbers. No error message is displayed whenever I attempt to search for an accession number. Would you know if something's wrong ? 
By the way, would you know if some kind of master file/table, in which one could find all the cCREs and the genes they can potentially target? That would be really useful if it exists. Thanks for taking the time to investigate this if you can, it would help a lot.
EDIT : An example of a search I would try below, with the result:
![github_issue1](https://user-images.githubusercontent.com/97189680/149909769-0fe20cd4-d995-47b9-873c-6190b5ff2c26.png)
![github_issue2](https://user-images.githubusercontent.com/97189680/149909774-a5cda0b7-8293-4cbd-b036-51f53f42ed13.png)

**Comment by Jill-Moore** [comment]
Thanks for bringing this to our attention. I will get make sure that this gets resolved ASAP

**Comment by skeitaa** [comment]
Thank you!

**Comment by hpratt** [comment]
Hello, we've deployed a fix that should resolve the cCRE search issues. The cCRE accession shown above is actually from Version 2 of the Registry of cCREs (see here for more information on Registry versions: https://screen.wenglab.org/index/cversions). The site will now let you know that is the case and offer to redirect you to the V2 page. Please let me know if you experience any other problems searching by accession and we'll be happy to look into them!

Regarding cCRE/target gene links, we are in the process of finalizing a list and will upload soon. When the list becomes available you will be able to download it using the purple "cCRE-gene links" buttons on the "Downloads" tab at the top of the homepage.

**Comment by skeitaa** [comment]
Hello, it looks like it works, thanks a lot ! The list would be a great feature to have, thanks for the great tools you provide.
